### ISSUE TITLE
The pictures in WIKI are unlinked

### ISSUE THREAD

**Issue by tkc285** [rh01/raspi-driving-car#2]
This is a great project for beginner and the WIKI gives an extra details.

Thank you very much for put it together.

Best regards!!

**Comment by rh01** [comment]
> This is a great project for beginner and the WIKI gives an extra details.
> 
> Thank you very much for put it together.
> 
> Best regards!!

Please follow this tutorial: https://www.shenhengheng.xyz/files/respberry_doc.pdf
