### ISSUE TITLE
您好..急需帮助

### ISSUE THREAD

**Issue by lz130dd** [rh01/raspi-driving-car#3]
您好，我现在也在做这个项目作为毕设，我看了看您的代码，您应该也是看了hamuchiwa和其他人的代码然后综合了一下。 我现在训练有些问题，准确率很低，我想请问一下您最后用的是哪个方法？cnn还是mlp 还是不带conv的keras? 哪个效果好一点？ 
还有就是大概需要多少frames可以完成训练？@Hengheng Shen

**Comment by rh01** [comment]
> 您好，我现在也在做这个项目作为毕设，我看了看您的代码，您应该也是看了hamuchiwa和其他人的代码然后综合了一下。 我现在训练有些问题，准确率很低，我想请问一下您最后用的是哪个方法？cnn还是mlp 还是不带conv的keras? 哪个效果好一点？
> 还有就是大概需要多少frames可以完成训练？@hengheng Shen

我最后在真实物理环境下使用的mlp，因为模型简单，树莓派可以负载起。但是还是深度学习模型准确度高一点，但是当时我只是作为线下实验进行的对比。

大概收集两个跑道的样子，有60MB吧。大概300多个样本。

**Comment by lz130dd** [comment]
@rh01 谢谢您的回复~ 还想请问一下您最后可以实现在未经训练的新跑道上自动驾驶吗？

**Comment by rh01** [comment]
> @rh01 谢谢您的回复~ 还想请问一下您最后可以实现在未经训练的新跑道上自动驾驶吗？

可以的。

**Comment by lz130dd** [comment]
@rh01 最后一个问题， 您当时准确率大概有多少呢

**Comment by rh01** [comment]
> @rh01 最后一个问题， 您当时准确率大概有多少呢

0.89

**Comment by Yuanbeijing** [comment]
你好，我想问一下怎么实现的左前控制？

**Comment by rh01** [comment]
> 你好，我想问一下怎么实现的左前控制？

左，前两个方向的pwm值不同即可实现。

**Comment by Yuanbeijing** [comment]
好的，谢谢！
我也是想这样实现，但是看代码里面没有涉及PWM的东西，嘿嘿。
