### ISSUE TITLE
关于材料

### ISSUE THREAD

**Issue by ForresterLu** [rh01/raspi-driving-car#4]
你好，我也想做一下你这个车子，请问你的RC-car选的就是一般的遥控汽车吗？

**Comment by rh01** [comment]
这个需要看遥控汽车的遥控器是否能够改装。

**Comment by ForresterLu** [comment]
那种算是可以改造的遥控器？

**Comment by ForresterLu** [comment]
可以提供一下你的链接吗？

**Comment by rh01** [comment]
google搜索 “Hacking a Toy RC Car Rx Board”，基本上大多数都可以改装

**Comment by ForresterLu** [comment]
好的，感谢
